sana_config: configs/sana_video_config/Sana_2000M_480px_AdamW_fsdp_chunk.yaml
sana_inference_config: configs/sana_video_config/Sana_2000M_480px_adamW_fsdp_longsana.yaml
generator_ckpt: hf://Efficient-Large-Model/SANA-Video_2B_480p/checkpoints/SANA_Video_2B_480p.pth
generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
model_name: SANA
text_encoder_fsdp_wrap_strategy: size
denoising_step_list:
  - 1000
  - 960
  - 889
  - 727
  - 0
warp_denoising_step: false # need to remove - 0 in denoising_step_list if warp_denoising_step is true
ts_schedule: false
num_train_timestep: 1000
timestep_shift: 7.0
mixed_precision: true
seed: 0
wandb_key: null
wandb_entity: null
wandb_project: self-forcing-sana
sharding_strategy: full
lr: 2.0e-05 #1.0e-05
beta1: 0.9
beta2: 0.999
data_path: output/LongSANA
batch_size: 1
gradient_accumulation_steps: 1
total_batch_size: null
log_iters: 200
max_checkpoints: 50
max_iters: 10000
motion_score: 10
negative_prompt: "A chaotic sequence with misshapen, deformed limbs in heavy motion blur, sudden disappearance, jump cuts, jerky movements, rapid shot changes, frames out of sync, inconsistent character shapes, temporal artifacts, jitter, and ghosting effects, creating a disorienting visual experience."
image_or_video_shape:
  - 1
  - 21 # T
  - 16
  - 60
  - 104
distribution_loss: ode
trainer: ode
gradient_checkpointing: true
num_frame_per_block: 10
independent_first_frame: false
load_raw_video: false
model_kwargs:
  local_attn_size: 21
  timestep_shift: 7.0
vis_interval: 200
vis_video_lengths:
  - 21
val_batch_size: 1
val_data_path: data/longsana/vidprom_filtered_extended.txt
num_training_frames: 21
slice_last_frames: 21
